# Generated by Django 5.0.7 on 2024-11-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='conversation',
            name='context_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
